---
- hosts: all
  become: yes
  vars:
    xmx_size: 512
    xmx_perm_size: 256
    tomcat_user: admin
    tomcat_passwd: sagar
    additional_packages:
      - tomcat7-docs
      - tomcat7-admin 
      - tomcat7-examples

  tasks: 
  - name: update ubuntu packages & install tomcat8
    package:
      name: tomcat8
      update_cache: yes
      state: present
  
  - name: copy tomcat8 file 
    template:
      src: templates/tomcat8.j2
      dest: etc/default/tomcat8
    notify:
    - restart tomcat8
  - name: copy tomca users file
    template:
      src: templates/tomcat-users.xml.j2
      dest: /etc/tomcat8/tomcat-users.xml
    notify:
    - restart tomcat8
  - name: install additional packages
    package:
      name: "{{ item }}"
      state: present
    loop: "{{  additional_packages }}"
  - name: install java
    package:
      name: default-jdk
      state: present
  handlers:
    name: restart tomcat
    service:
      name: tomcat8
      state: restarted
